CREATE TABLE skill
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255),
    CONSTRAINT pk_skill PRIMARY KEY (id)
);

CREATE TABLE proof_skill
(
    proof_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL
);

ALTER TABLE proof_skill
    ADD CONSTRAINT fk_proski_on_proof FOREIGN KEY (proof_id) REFERENCES proof (id) ON DELETE CASCADE;

ALTER TABLE proof_skill
    ADD CONSTRAINT fk_proski_on_skill FOREIGN KEY (skill_id) REFERENCES skill (id);

INSERT INTO skill (title)
VALUES
    ('Java'),
    ('Python'),
    ('C/C++'),
    ('C#/.NET'),
    ('Verilog'),
    ('Swift'),
    ('Ruby'),
    ('Kotlin'),
    ('Objective-C'),
    ('Scala'),
    ('PHP'),
    ('HTML'),
    ('CSS'),
    ('JavaScript'),
    ('XML'),
    ('Shell'),
    ('Rust'),
    ('TypeScript'),
    ('Go'),
    ('PostgreSQL'),
    ('MySQL'),
    ('MSSQL'),
    ('OracleDB'),
    ('MongoDB'),
    ('Redis'),
    ('AmazonDynamoDB'),
    ('Git'),
    ('IOS'),
    ('Google'),
    ('Azure'),
    ('Linux'),
    ('Windows'),
    ('Android'),
    ('IBM'),
    ('Figma'),
    ('Photoshop'),
    ('Adobe.XD'),
    ('Docker'),
    ('Kubernetes'),
    ('Helm'),
    ('Terraform'),
    ('Jenkins'),
    ('Verilog'),
    ('Jest'),
    ('Mocha '),
    ('Supertest'),
    ('Puppeteer'),
    ('WebDriverIO'),
    ('Jira'),
    ('Postman'),
    ('Cypress'),
    ('TestRail'),
    ('Animator'),
    ('Blockchain'),
    ('Design');


INSERT INTO proof_skill (proof_id, skill_id)
VALUES
    (1,1);