DROP TABLE IF EXISTS kudos;

CREATE TABLE kudos
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sponsor_id BIGINT,
    proof_id   BIGINT                                  NOT NULL,
    skill_id   BIGINT                                  NOT NULL,
    amount     INTEGER,
    kudos_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_kudos PRIMARY KEY (id)
);

ALTER TABLE kudos
    ADD CONSTRAINT FK_KUDOS_ON_PROOF FOREIGN KEY (proof_id) REFERENCES proof (id) ON DELETE CASCADE;

ALTER TABLE kudos
    ADD CONSTRAINT FK_KUDOS_ON_SKILL FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE;

ALTER TABLE kudos
    ADD CONSTRAINT FK_KUDOS_ON_SPONSOR FOREIGN KEY (sponsor_id) REFERENCES sponsor (sponsor_id) ON DELETE CASCADE;

INSERT INTO kudos (sponsor_id, proof_id, amount, kudos_date, skill_id) VALUES
    (28, 5, 10, '2023-05-19 12:08', 12);

ALTER TABLE talent ADD COLUMN balance INTEGER;