CREATE TABLE talent
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(254),
    password VARCHAR(64),
    name     VARCHAR(64),
    surname  VARCHAR(64),
    CONSTRAINT pk_talent PRIMARY KEY (id)
);

CREATE TABLE talent_info
(
    talent_id  BIGINT NOT NULL,
    image      VARCHAR(255),
    experience VARCHAR(254),
    location   VARCHAR(32),
    phone      VARCHAR(16),
    age        date,
    education  VARCHAR(64),
    about      VARCHAR(1000),
    CONSTRAINT pk_talentinfo PRIMARY KEY (talent_id)
);

ALTER TABLE talent_info
    ADD CONSTRAINT FK_TALENTINFO_ON_TALENT FOREIGN KEY (talent_id) REFERENCES talent (id) ON DELETE CASCADE;


CREATE TABLE Proof (
    Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    publication_date DATE NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    talent_id INT NOT NULL,
    CONSTRAINT fk_talent FOREIGN KEY (talent_id) REFERENCES Talent(Id) ON DELETE CASCADE
);

CREATE DOMAIN ProofStatus AS VARCHAR(20) CHECK (VALUE IN ('DRAFT', 'HIDDEN', 'PUBLISHED'));

/*CREATE TABLE Proof (*/
/*    id SERIAL PRIMARY KEY NOT NULL,*/
/*    publication_date DATE,*/
/*    title VARCHAR(255) NOT NULL,*/
/*    description TEXT NOT NULL,*/
/*    status ProofStatus NOT NULL,*/
/*    talent_id INT NOT NULL REFERENCES Talent(Id) ON DELETE CASCADE*/
/*);*/
/**/
/*CREATE TYPE ProofStatus AS ENUM ('DRAFT', 'HIDDEN', 'PUBLISHED');*/