name: React CI

on:
  workflow_dispatch: 
  push:
    branches:
      - "dev"


jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        java-version: [16.x]
        
    steps:
      - uses: actions/checkout@v1
      - run: pkill java
      - run: mvn clean package
